[package]
name = "flash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = { version = "0.16", default-features = false, features = ['crossterm'] }
crossterm =  "0.23"
serde =  { version = "1.0.137", optional = false, features = ["derive"]}
serde_derive = "1.0.137"
serde_json = "1.0.81"
rusqlite = "0.27.0"
chrono = "0.4.19"
bitflags = "1.3"
#cassowary = "0.3"
#unicode-segmentation = "1.2"
#unicode-width = "0.1"
#termion = { version = "1.5", optional = true }
